{% set name = "opentelemetry-instrumentation-urllib3" %}
{% set version = "0.50b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_urllib3-{{ version }}.tar.gz
  sha256: 2c4a1d9f128eaf753871b1d90659c744691d039a6601ba546081347ae192bd0e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.50b0
    - opentelemetry-semantic-conventions ==0.50b0
    - opentelemetry-util-http ==0.50b0
    - wrapt <2.0.0,>=1.0.0
    # - urllib3 <2.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-urllib3 
    # - httpretty ~=1.0
    # - urllib3 <2.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-urllib3 
    # - httpretty ~=1.0
    # - urllib3 <2.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-urllib3 
    # - httpretty ~=1.0
    # - urllib3 <3.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-urllib3 
    # - httpretty ~=1.0
    # - urllib3 <3.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-urllib3 
    # - httpretty ~=1.0
    # - urllib3 <3.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-urllib3 
    # - httpretty ~=1.0
    # - urllib3 <3.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-urllib3 
    # - httpretty ~=1.0
    # - urllib3 <3.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-urllib3 
    # - httpretty ~=1.0
    # - urllib3 <3.0.0,>=1.0.0
    # - urllib3 <3.0.0,>=1.0.0
    # - urllib3 <3.0.0,>=1.0.0
    # - urllib3 <3.0.0,>=1.0.0
    # - urllib3 <3.0.0,>=1.0.0
    # - urllib3 <3.0.0,>=1.0.0
    # - urllib3 <3.0.0,>=1.0.0
    # - urllib3 <3.0.0,>=1.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-urllib3
  summary: OpenTelemetry urllib3 instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
