{% set name = "opentelemetry-instrumentation-urllib3" %}
{% set version = "0.25b2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-urllib3-{{ version }}.tar.gz
  sha256: 19d7a2d650f0807378d376ba7414d01057f66ac11248ea189ab5be842b2bc845

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.25b2
    - opentelemetry-semantic-conventions ==0.25b2
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - urllib3 <2.0.0,>=1.0.0
    # - opentelemetry-test ==0.24b0
    # - httpretty ~=1.0
    # - urllib3 <2.0.0,>=1.0.0
    # - opentelemetry-util-http ==0.25b2
    # - opentelemetry-test ==0.25b2
    # - httpretty ~=1.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-urllib3
  summary: OpenTelemetry urllib3 instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
