{% set name = "opentelemetry-instrumentation-urllib3" %}
{% set version = "0.40b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_urllib3-{{ version }}.tar.gz
  sha256: 10b633781e7466cde6e3042d3642a22131867aceadd1a0e10912e08718cfa7ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.40b0
    - opentelemetry-semantic-conventions ==0.40b0
    - opentelemetry-util-http ==0.40b0
    - wrapt <2.0.0,>=1.0.0
    # - urllib3 <2.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-urllib3 
    # - httpretty ~=1.0
    # - urllib3 <2.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-urllib3 
    # - httpretty ~=1.0
    # - urllib3 <2.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-urllib3 
    # - httpretty ~=1.0
    # - urllib3 <3.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-urllib3 
    # - httpretty ~=1.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-urllib3
  summary: OpenTelemetry urllib3 instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
